version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  fastapi_app:
    build: .
    container_name: fastapi_chatbot
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ["/bin/sh", "-c", "./init-db.sh && exec uvicorn main:app --host 0.0.0.0 --port 8000"]

volumes:
  postgres_data:
