"""Initial tables

Revision ID: 3904d1bbbaca
Revises: 2f1784ca12bf
Create Date: 2025-01-22 14:12:53.940229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3904d1bbbaca'
down_revision: Union[str, None] = '2f1784ca12bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
